### ISSUE TITLE
from toad.plot import bin_plot 报错

### ISSUE THREAD

**Issue by Ausar0109** [amphibian-dev/toad#8]
from toad.plot import bin_plot
Traceback (most recent call last):
  File "C:\miniconda\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\miniconda\lib\site-packages\toad\plot.py", line 6, in <module>
    from .tadpole import tadpole
  File "C:\miniconda\lib\site-packages\toad\tadpole\__init__.py", line 5, in <module>
    from .base import Tadpole
  File "C:\miniconda\lib\site-packages\toad\tadpole\base.py", line 2, in <module>
    from .utils import (
  File "C:\miniconda\lib\site-packages\toad\tadpole\utils.py", line 16, in <module>
    HEATMAP_CMAP = sns.diverging_palette(240, 10, as_cmap = True)
  File "C:\miniconda\lib\site-packages\seaborn\palettes.py", line 744, in diverging_palette
    neg = palfunc((h_neg, s, l), 128 - (sep / 2), reverse=True, input="husl")
  File "C:\miniconda\lib\site-packages\seaborn\palettes.py", line 641, in light_palette
    return blend_palette(colors, n_colors, as_cmap)
  File "C:\miniconda\lib\site-packages\seaborn\palettes.py", line 777, in blend_palette
    pal = _ColorPalette(pal(np.linspace(0, 1, n_colors)))
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\miniconda\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

numpy 和 cpython都是最新

**Comment by Ausar0109** [comment]
之前用的miniconda ，要用的包都自己装-
---------------
重新安装了2019.10最新的anconda 发行版，只运行了pip install toad 解决
应该是自己装包的包版本友好度没有官方的强原因，溯源原因没找到

**Comment by Secbone** [comment]
多谢反馈，这个原因应该是 seaborn 没有对最新的 numpy 做支持导致的，下个版本我会调整一下依赖版本 :)
